"""AI evaluation harness (Phase 12, PLAN.md §31).

"Do not say the AI works without evaluation." Loads every case in
examples/*.json, runs it through the real process_invoice pipeline (the
same function 07-api or a future posting workflow would call -- this
isn't a separate, simplified evaluation path), and measures:

- classification accuracy (did the suggestion match ground truth?)
- false positives / negatives, defined against the REVIEW-ROUTING
  decision (not the raw classification), since that's the decision this
  system actually makes: a "positive" is "flagged for human review"
    - false positive: flagged for review, but the suggestion was actually
      correct (safe, but a wasted review)
    - false negative: NOT flagged for review, but the suggestion was
      actually incorrect (the dangerous case)
- percentage routed to human review
- inappropriate_automation_rate: the false-negative rate, called out
  under its own name because PLAN.md §31 is explicit that this is the
  most important number here, not raw accuracy. An AI that's 90%
  "accurate" but wrong on the 10% it also auto-approves is far more
  dangerous than one that's 70% accurate but never auto-approves a wrong
  answer.

Every case here uses MockLLMClient (see llm_client.py's docstring for
why) -- these numbers describe how the safety-policy pipeline behaves
given a range of model outputs, not a real model's classification
accuracy. Re-run this same script against AnthropicLLMClient's output
once a real API key is available to get real model numbers; the
methodology doesn't change.

Run from the repo root: .venv/bin/python 09-ai/evaluate.py
"""

from __future__ import annotations

import json
from pathlib import Path

from accounting_agent import process_invoice
from llm_client import LLMSuggestion, MockLLMClient

EXAMPLES_DIR = Path(__file__).resolve().parent / "examples"
REPORT_PATH = Path(__file__).resolve().parent / "evaluation-results.md"


def load_case(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def run_case(case: dict) -> dict:
    invoice = case["invoice"]
    suggestion = LLMSuggestion(**case["mock_response"])
    client = MockLLMClient({invoice["invoice_id"]: suggestion})

    result = process_invoice(
        invoice, client, case["known_accounts"], case["known_entities"],
        vendor_default_account_code=case["vendor_default_account_code"],
        amount=invoice["amount"],
        vendor_historical_amounts=case.get("vendor_historical_amounts"),
    )

    gt = case["ground_truth"]
    suggestion_correct = (
        result.suggested_account_code == gt["correct_account_code"]
        and result.suggested_entity_code == gt["correct_entity_code"]
    )

    if result.requires_human_review and suggestion_correct:
        review_outcome = "false_positive"  # flagged, but was fine -- safe, just extra work
    elif result.requires_human_review and not suggestion_correct:
        review_outcome = "true_positive"  # flagged, and rightly so
    elif not result.requires_human_review and suggestion_correct:
        review_outcome = "true_negative"  # auto-approved, correctly
    else:
        review_outcome = "false_negative"  # auto-approved, but WRONG -- inappropriate automation

    return {
        "invoice_id": invoice["invoice_id"],
        "category": case["category"],
        "suggestion_correct": suggestion_correct,
        "requires_human_review": result.requires_human_review,
        "review_reasons": result.review_reasons,
        "review_outcome": review_outcome,
    }


def run() -> None:
    cases = sorted(EXAMPLES_DIR.glob("*.json"))
    results = [run_case(load_case(path)) for path in cases]

    total = len(results)
    accuracy = sum(r["suggestion_correct"] for r in results) / total
    pct_routed = sum(r["requires_human_review"] for r in results) / total
    false_positives = [r for r in results if r["review_outcome"] == "false_positive"]
    false_negatives = [r for r in results if r["review_outcome"] == "false_negative"]
    true_positives = [r for r in results if r["review_outcome"] == "true_positive"]
    true_negatives = [r for r in results if r["review_outcome"] == "true_negative"]
    inappropriate_automation_rate = len(false_negatives) / total

    with open(REPORT_PATH, "w") as f:
        f.write("# AI Evaluation Results — Phase 12 (PLAN.md §31)\n\n")
        f.write(
            f"Generated by `evaluate.py` against {total} hand-built cases in `examples/`, "
            "run through the real `process_invoice` pipeline with `MockLLMClient` standing "
            "in for a real model (see `llm_client.py`'s docstring — these numbers describe "
            "the safety-policy pipeline's behaviour, not a real model's accuracy).\n\n"
        )
        f.write("## Headline metrics\n\n")
        f.write(f"- **Classification accuracy:** {accuracy:.0%} ({sum(r['suggestion_correct'] for r in results)}/{total})\n")
        f.write(f"- **Routed to human review:** {pct_routed:.0%} ({sum(r['requires_human_review'] for r in results)}/{total})\n")
        f.write(f"- **False positives** (flagged, but suggestion was fine): {len(false_positives)}/{total}\n")
        f.write(f"- **False negatives** (auto-approved, but suggestion was WRONG): {len(false_negatives)}/{total}\n")
        f.write(
            f"- **Inappropriate automation rate: {inappropriate_automation_rate:.0%}** "
            f"({len(false_negatives)}/{total}) — the most important number here, per PLAN.md §31, "
            "not the accuracy figure above.\n\n"
        )
        f.write("## Per-case detail\n\n")
        f.write("| Invoice | Category | Correct? | Reviewed? | Outcome | Reasons |\n")
        f.write("|---|---|---|---|---|---|\n")
        for r in results:
            reasons = "; ".join(r["review_reasons"]) or "—"
            f.write(
                f"| {r['invoice_id']} | {r['category']} | {'✓' if r['suggestion_correct'] else '✗'} | "
                f"{'yes' if r['requires_human_review'] else 'no'} | {r['review_outcome']} | {reasons} |\n"
            )

    print(f"wrote {REPORT_PATH}")
    print(f"accuracy={accuracy:.0%} routed_to_review={pct_routed:.0%} "
          f"inappropriate_automation_rate={inappropriate_automation_rate:.0%} "
          f"(FP={len(false_positives)} FN={len(false_negatives)} TP={len(true_positives)} TN={len(true_negatives)})")


if __name__ == "__main__":
    run()
