"""Runs the Phase 13 reconciliation engine against the real northstar
database and writes reconciliation-engine-results.md -- the same "prove
it against real data" pattern as every prior phase.

Run from the repo root: .venv/bin/python 06-python/run_reconciliation.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from db import get_engine
from reconciliation_engine import MatchResult, reconcile_ap, reconcile_bank, reconcile_intercompany

REPORT_PATH = Path(__file__).resolve().parent / "reconciliation-engine-results.md"


def run() -> None:
    engine = get_engine()

    bank_df = pd.read_sql("SELECT * FROM bank_transactions", engine)
    payments_df = pd.read_sql("SELECT * FROM payments", engine)
    invoices_df = pd.read_sql("SELECT * FROM invoices", engine)
    ic_df = pd.read_sql("SELECT * FROM intercompany_transactions", engine)

    bank_results = reconcile_bank(bank_df, payments_df)
    ap_results = reconcile_ap(invoices_df, payments_df)
    ic_results = reconcile_intercompany(ic_df)

    write_report(bank_results, ap_results, ic_results)


def summarize(results: list[MatchResult]) -> dict[str, int]:
    counts = {"matched": 0, "probable_match": 0, "unmatched": 0}
    for r in results:
        counts[r.match_status] += 1
    return counts


def write_report(bank_results, ap_results, ic_results) -> None:
    sections = [("Bank", bank_results), ("AP", ap_results), ("Intercompany", ic_results)]

    with open(REPORT_PATH, "w") as f:
        f.write("# Reconciliation Engine Results — Phase 13 (PLAN.md §26)\n\n")
        f.write(
            "Generated by `run_reconciliation.py` against the real `northstar` database. "
            "Four-tier output (matched / probable_match / unmatched, each with a reason where "
            "not a clean match) for the three areas PLAN.md §26 asks for.\n\n"
        )

        f.write("## Summary\n\n")
        f.write("| Area | Matched | Probable Match | Unmatched | Total |\n|---|---|---|---|---|\n")
        for name, results in sections:
            counts = summarize(results)
            total = len(results)
            f.write(f"| {name} | {counts['matched']} | {counts['probable_match']} | {counts['unmatched']} | {total} |\n")
        f.write("\n")

        for name, results in sections:
            f.write(f"## {name}\n\n")
            f.write("| ID | Status | Matched To | Reason |\n|---|---|---|---|\n")
            for r in sorted(results, key=lambda x: (x.match_status != "unmatched", x.match_status != "probable_match", x.subject_id)):
                matched_to = r.matched_id or "—"
                reason = r.exception_reason or "—"
                f.write(f"| {r.subject_id} | {r.match_status} | {matched_to} | {reason} |\n")
            f.write("\n")

    print(f"wrote {REPORT_PATH}")
    for name, results in sections:
        print(f"  {name}: {summarize(results)}")


if __name__ == "__main__":
    run()
